openapi: "3.0.3"
info:
  title: TimeRange Model
  version: "1.0"

components:
  schemas:
    Event:
      type: object
      properties:
        dtstart:
          type: string
          format: date-time
        dtend:
          type: string
          format: date-time
        rrule:
          $ref: '#/components/schemas/RecurrenceRule'

    RecurrenceRule:
      type: object
      properties:
        freq:
          $ref: '#/components/schemas/Frequency'
        until:
          type: string
          format: date-time
        count:
          type: integer
        interval:
          type: integer
        byday:
          description: day on which to repeat
          type: array
          items:
            $ref: '#/components/schemas/Weekday'
        bymonth:
          description: month in which to repeat
          $ref: '#/components/schemas/MonthNum'
        bymonthday:
          description: day of the month on which to repeat
          $ref: '#/components/schemas/MonthDayNum'
        bysetpos:
          description: repeat on the first, second, third...
          type: integer


    Frequency:
      type: string
      enum:
        - SECONDLY
        - MINUTELY
        - HOURLY
        - DAILY
        - WEEKLY
        - MONTHLY
        - YEARLY

    Weekday:
      description: days of the week
      type: string
      nullable: true
      enum:
        - MO
        - TU
        - WE
        - TH
        - FR
        - SA
        - SU

    MonthDayNum:
      type: integer
      minimum: 1
      maximum: 31

    MonthNum:
      type: integer
      minimum: 1
      maximum: 12


