name: Test, Build and Publish

on:
  push:
  workflow_dispatch:
    # Map workflow outputs to job outputs
    outputs:
      build-image:
        description: "Vue build image"
        value: ${{ jobs.test.outputs.build-image }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/more-study-manager-frontend

jobs:
  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      build-image: steps.build
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: 3rd-Party Licenses
        run: |
          mkdir -p target/
          npm --silent run license:list > target/THIRD_PARTY.txt
          cat target/THIRD_PARTY.txt

      - name: Upload License List
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: 3rd Party Licenses
          path: "target/THIRD_PARTY.txt"

      - name: Check licenses
        run: npm run license:check

      #      - name: Run tests
      #        run: npm run test:unit:once
      #
      #      - name: Upload Test Results
      #        if: always()
      #        uses: actions/upload-artifact@v3
      #        with:
      #          name: Test Results
      #          path: "target/testResults.xml"

      - name: Run build
        id: build
        run: npm run package

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Event File
          path: ${{ github.event_path }}
